-- Run this once in Supabase SQL Editor.

do $$
begin
  begin
    alter publication supabase_realtime add table public.leads;
  exception when duplicate_object then
    null;
  end;
  begin
    alter publication supabase_realtime add table public.users;
  exception when duplicate_object then
    null;
  end;
end $$;

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  actor_name text not null,
  actor_role text not null,
  activity_type text not null check (activity_type in ('call', 'comment', 'assignment', 'forward')),
  outcome text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.activity_logs enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'activity_logs' and policyname = 'Authenticated users can read activity logs') then
    create policy "Authenticated users can read activity logs"
      on public.activity_logs for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'activity_logs' and policyname = 'Users can add their activity logs') then
    create policy "Users can add their activity logs"
      on public.activity_logs for insert to authenticated with check (auth.uid() = actor_id);
  end if;
end $$;

create index if not exists activity_logs_lead_created_idx
  on public.activity_logs (lead_id, created_at desc);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'assignment',
  title text not null,
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

do $$
begin
  begin
    alter publication supabase_realtime add table public.activity_logs;
  exception when duplicate_object then
    null;
  end;
  begin
    alter publication supabase_realtime add table public.notifications;
  exception when duplicate_object then
    null;
  end;
end $$;

alter table public.notifications enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notifications' and policyname = 'Users can read their notifications') then
    create policy "Users can read their notifications"
      on public.notifications for select to authenticated using (user_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notifications' and policyname = 'Authenticated users can create notifications') then
    create policy "Authenticated users can create notifications"
      on public.notifications for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notifications' and policyname = 'Users can update their notifications') then
    create policy "Users can update their notifications"
      on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

alter table public.leads
  add column if not exists customer_number bigint generated by default as identity;

create unique index if not exists leads_customer_number_unique
  on public.leads (customer_number)
  where customer_number is not null;

alter table public.leads
  add column if not exists website text;

alter table public.leads
  add column if not exists website_key text;

create unique index if not exists leads_website_key_unique
  on public.leads (website_key);

alter table public.leads
  add column if not exists quantity integer not null default 0
  check (quantity >= 0);

create or replace function public.set_lead_customer_number(target_lead_id uuid, new_customer_number bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if new_customer_number is not null and new_customer_number <= 0 then
    raise exception 'Customer number must be positive';
  end if;

  update public.leads
  set customer_number = new_customer_number
  where id = target_lead_id;
end;
$$;

grant execute on function public.set_lead_customer_number(uuid, bigint) to authenticated;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'leads' and policyname = 'Admins can delete leads') then
    create policy "Admins can delete leads"
      on public.leads for delete
      to authenticated
      using (exists (select 1 from public.users where id = auth.uid() and role = 'admin'));
  end if;
end $$;

alter table public.leads
  add column if not exists is_salla_store boolean not null default false;

alter table public.leads
  add column if not exists data_quality text not null default 'normal'
  check (data_quality in ('high', 'medium', 'normal'));

alter table public.leads
  add column if not exists website_status text
  check (website_status in ('working', 'not_working'));

alter table public.leads
  add column if not exists website_status_source text
  check (website_status_source in ('manual', 'auto_checked'));

alter table public.leads
  add column if not exists phone_source text
  check (phone_source in ('manual', 'website'));

alter table public.leads
  drop constraint if exists leads_phone_source_check;

alter table public.leads
  add constraint leads_phone_source_check
  check (phone_source in ('manual', 'website', 'auto_scraped'));

update public.leads
set phone_source = 'manual'
where phone is not null and phone_source is null;

update public.leads
set website_status_source = 'manual'
where website_status is not null and website_status_source is null;

create table if not exists public.client_comments (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  text text not null check (char_length(trim(text)) > 0),
  created_at timestamptz not null default now()
);

alter table public.client_comments enable row level security;

create policy "Authenticated users can read client comments"
  on public.client_comments for select
  to authenticated using (true);

create policy "Authenticated users can add client comments"
  on public.client_comments for insert
  to authenticated with check (auth.uid() = author_id);

create or replace function public.delete_user_account(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not exists (
    select 1 from public.users
    where id = auth.uid() and role = 'admin'
  ) then
    raise exception 'Only admins can delete users';
  end if;

  if target_user_id = auth.uid() then
    raise exception 'The current admin cannot delete their own account';
  end if;

  delete from auth.users where id = target_user_id;
end;
$$;

grant execute on function public.delete_user_account(uuid) to authenticated;

-- Refresh PostgREST so the browser can see the function immediately.
notify pgrst, 'reload schema';

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Managers can read their team') then
    create policy "Managers can read their team"
      on public.users for select
      to authenticated
      using (id = auth.uid() or manager_id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'leads' and policyname = 'Managers can read team leads') then
    create policy "Managers can read team leads"
      on public.leads for select
      to authenticated
      using (
        assigned_to = auth.uid()
        or exists (
          select 1 from public.users team_member
          where team_member.id = leads.assigned_to
            and team_member.manager_id = auth.uid()
        )
      );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'leads' and policyname = 'Managers can assign team leads') then
    create policy "Managers can assign team leads"
      on public.leads for update
      to authenticated
      using (
        assigned_to = auth.uid()
        or exists (
          select 1 from public.users team_member
          where team_member.id = leads.assigned_to
            and team_member.manager_id = auth.uid()
        )
      )
      with check (
        assigned_to = auth.uid()
        or exists (
          select 1 from public.users team_member
          where team_member.id = leads.assigned_to
            and team_member.manager_id = auth.uid()
        )
      );
  end if;
end $$;
